
# true ou false
# operador relacional de iguldade


# fazer um sistema de conferêcia de idade.
# para responder as seguintes perguntas:

#A idade é igual a 18? ok
#A idade é diferente a 18 ok
#A idade é maior a 18? ok
#A idade é menor a 18 ok
#A idade é maior ou igual a 18?
#A idade é menor ou igual a 18?

# sinais ==, !=, >, <, >=, <=

validador = True
idade = int(input("Digite sua idade>>"))

validador = (idade == 18)
print (f"a idade é igual a 18? {validador}")

validador = (idade != 18)
print (f"a idade é diferente a 18? {validador}")

validador = (idade > 18)
print (f"a idade é maior a 18? {validador}")

validador = (idade < 18)
print (f"a idade é menor a 18? {validador}")

validador = (idade >= 18)
print (f"a idade é maior igual a 18? {validador}")

validador = (idade <= 18)
print (f"a idade é menor igual a 18? {validador}")




#print (f" o seu nome é {nome} \n o seu sobrenome é{sobrenome} \n e a sua idade é {idade}")
# => print ("o nome digitado foi: {} \n o sobrenome digitado foi: {} \n e a idade digitada foi:{}". format(nome, sobrenome, idade))



validador = (idade ==18)
print ("a idade é igual a 18? {}".format(validador))

validador = (idade != 18)
print ("a idade é diferente a 18? {}".format(validador))

validador = (idade >18)
print ("a idade é maior a 18? {}".format(validador))

validador = (idade <18)
print ("a idade é menor a 18? {}".format(validador))

validador = (idade >=18)
print ("a idade é maior igual a 18? {}".format(validador))

validador = (idade <=18)
print ("a idade é menor igual a 18? {}".format(validador))



validador = (idade == 18)
print ("a idade é igual a 18?:", validador)

validador = (idade !=18)
print ("a idade é diferente a 18?:", validador)

validador = (idade >18)
print ("a idade é maior a 18?:", validador)

validador = (idade <18)
print ("a idade é menor a 18?:", validador)

validador = (idade >=18)
print ("a idade é maior igual a 18?:", validador)

validador = (idade <=18)
print ("a idade é menor igual a 18?:", validador)






